# Generated by Django 5.0.4 on 2024-05-16 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_username_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='owener',
            new_name='owner',
        ),
    ]
