# Generated by Django 5.0.4 on 2024-04-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('Round', 'Round'), ('Bar', 'Bar'), ('Misc', 'Miscellaneous')], max_length=10)),
                ('agw', models.DecimalField(decimal_places=4, max_digits=10)),
                ('purity', models.DecimalField(decimal_places=6, max_digits=15)),
                ('quantity', models.IntegerField()),
                ('weight_troy_oz', models.DecimalField(decimal_places=4, max_digits=10)),
                ('cost_to_purchase', models.DecimalField(decimal_places=2, max_digits=20)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('coa_present', models.BooleanField(default=False)),
                ('purchased_from', models.CharField(max_length=100)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Gold',
            },
        ),
        migrations.CreateModel(
            name='Platinum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('Round', 'Round'), ('Bar', 'Bar'), ('Misc', 'Miscellaneous')], max_length=10)),
                ('agw', models.DecimalField(decimal_places=4, max_digits=10)),
                ('purity', models.DecimalField(decimal_places=6, max_digits=15)),
                ('quantity', models.IntegerField()),
                ('weight_troy_oz', models.DecimalField(decimal_places=4, max_digits=10)),
                ('cost_to_purchase', models.DecimalField(decimal_places=2, max_digits=20)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('coa_present', models.BooleanField(default=False)),
                ('purchased_from', models.CharField(max_length=100)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Platinum',
            },
        ),
        migrations.CreateModel(
            name='Silver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('Round', 'Round'), ('Bar', 'Bar'), ('Misc', 'Miscellaneous')], max_length=10)),
                ('agw', models.DecimalField(decimal_places=4, max_digits=10)),
                ('purity', models.DecimalField(decimal_places=6, max_digits=15)),
                ('quantity', models.IntegerField()),
                ('weight_troy_oz', models.DecimalField(decimal_places=4, max_digits=10)),
                ('cost_to_purchase', models.DecimalField(decimal_places=2, max_digits=20)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('coa_present', models.BooleanField(default=False)),
                ('purchased_from', models.CharField(max_length=100)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Silver',
            },
        ),
    ]
