# Generated by Django 5.0.6 on 2024-06-14 09:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0003_rename_owener_review_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gold',
            fields=[
                ('metal_type', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('platinum', 'Platinum')], default='', max_length=100)),
                ('item_type', models.CharField(choices=[('bar', 'Bar'), ('round', 'Round'), ('misc', 'Misc')], default='round', max_length=100)),
                ('coa_present', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=100)),
                ('item_year', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('item_name', models.CharField(max_length=100)),
                ('item_about', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('featured_image', models.ImageField(blank=True, default='images/gold_avatar.jpg', null=True, upload_to='')),
                ('purity', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('quantity', models.IntegerField()),
                ('weight_troy_oz', models.DecimalField(decimal_places=4, max_digits=30)),
                ('weight_grams', models.DecimalField(decimal_places=4, default=0.0, max_digits=30)),
                ('cost_to_purchase', models.DecimalField(decimal_places=2, max_digits=20)),
                ('spot_at_purchase', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True)),
                ('premium', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('purchased_from', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('weight_per_unit', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('initial_weight_unit', models.CharField(choices=[('GRAMS', 'Grams'), ('TROY_OUNCES', 'Troy Ounces')], default='TROY_OUNCES', max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sell_price', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('sold_to', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'verbose_name_plural': 'Gold',
            },
        ),
        migrations.CreateModel(
            name='Platinum',
            fields=[
                ('metal_type', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('platinum', 'Platinum')], default='', max_length=100)),
                ('item_type', models.CharField(choices=[('bar', 'Bar'), ('round', 'Round'), ('misc', 'Misc')], default='round', max_length=100)),
                ('coa_present', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=100)),
                ('item_year', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('item_name', models.CharField(max_length=100)),
                ('item_about', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('featured_image', models.ImageField(blank=True, default='images/platinum_avatar.jpg', null=True, upload_to='')),
                ('purity', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('quantity', models.IntegerField()),
                ('weight_troy_oz', models.DecimalField(decimal_places=4, max_digits=30)),
                ('weight_grams', models.DecimalField(decimal_places=4, default=0.0, max_digits=30)),
                ('cost_to_purchase', models.DecimalField(decimal_places=2, max_digits=20)),
                ('spot_at_purchase', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True)),
                ('premium', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('purchased_from', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('weight_per_unit', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('initial_weight_unit', models.CharField(choices=[('GRAMS', 'Grams'), ('TROY_OUNCES', 'Troy Ounces')], default='TROY_OUNCES', max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sell_price', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('sold_to', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'verbose_name_plural': 'Platinum',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sell_quantity', models.DecimalField(decimal_places=2, max_digits=30)),
                ('sold_to', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('date_sold', models.DateField(auto_now_add=True)),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Silver',
            fields=[
                ('metal_type', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('platinum', 'Platinum')], default='', max_length=100)),
                ('item_type', models.CharField(choices=[('bar', 'Bar'), ('round', 'Round'), ('misc', 'Misc')], default='round', max_length=100)),
                ('coa_present', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=100)),
                ('item_year', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('item_name', models.CharField(max_length=100)),
                ('item_about', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('featured_image', models.ImageField(blank=True, default='images/silver_avatar.jpg', null=True, upload_to='')),
                ('purity', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('quantity', models.IntegerField()),
                ('weight_troy_oz', models.DecimalField(decimal_places=4, max_digits=30)),
                ('weight_grams', models.DecimalField(decimal_places=4, default=0.0, max_digits=30)),
                ('cost_to_purchase', models.DecimalField(decimal_places=2, max_digits=20)),
                ('spot_at_purchase', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True)),
                ('premium', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('purchased_from', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('weight_per_unit', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('initial_weight_unit', models.CharField(choices=[('GRAMS', 'Grams'), ('TROY_OUNCES', 'Troy Ounces')], default='TROY_OUNCES', max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sell_price', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('sold_to', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'verbose_name_plural': 'Silver',
            },
        ),
    ]
