# Generated by Django 5.0.6 on 2024-06-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_sale_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='gold',
            name='total_cost_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='platinum',
            name='total_cost_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='silver',
            name='total_cost_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
    ]
