# Generated by Django 5.0.6 on 2024-06-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_gold_total_cost_per_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30),
        ),
    ]
