# Generated by Django 5.0.6 on 2024-06-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_sale_shipping_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
