# Generated by Django 5.0.6 on 2024-06-20 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_sale_shipping_cost'),
        ('users', '0003_rename_owener_review_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='MetalsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(default=0)),
                ('rates', models.JSONField()),
                ('currency', models.CharField(max_length=30)),
                ('current_gold_price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('current_silver_price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('current_platinum_price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
