# Generated by Django 5.0.4 on 2024-04-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_rename_coa_present_gold_coa_present_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gold',
            name='item_type',
            field=models.CharField(blank=True, choices=[('Round', 'Round'), ('Bar', 'Bar'), ('Misc', 'Miscellaneous')], max_length=10, null=True),
        ),
    ]
