# Generated by Django 5.0.6 on 2024-06-20 03:26

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_sale_sell_price_metalsdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetalsData',
        ),
    ]