# Generated by Django 5.0.4 on 2024-04-12 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_gold_item_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gold',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='platinum',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='silver',
            name='item_type',
        ),
    ]
