# Generated by Django 5.0.6 on 2024-06-20 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_metalsdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metalsdata',
            options={'verbose_name_plural': 'Metals Data'},
        ),
    ]
