# Generated by Django 5.0.4 on 2024-04-15 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_rename_name_gold_item_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gold',
            old_name='item_name',
            new_name='name',
        ),
    ]
