# Generated by Django 5.0.4 on 2024-04-15 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_rename_item_name_gold_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gold',
            old_name='name',
            new_name='item_name',
        ),
    ]
