# Generated by Django 5.0.6 on 2024-07-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_metalsdata_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gold',
            name='sell_price',
        ),
        migrations.RemoveField(
            model_name='gold',
            name='sold_to',
        ),
        migrations.RemoveField(
            model_name='platinum',
            name='sell_price',
        ),
        migrations.RemoveField(
            model_name='platinum',
            name='sold_to',
        ),
        migrations.RemoveField(
            model_name='silver',
            name='sell_price',
        ),
        migrations.RemoveField(
            model_name='silver',
            name='sold_to',
        ),
        migrations.AlterField(
            model_name='metalsdata',
            name='current_gold_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='metalsdata',
            name='current_platinum_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='metalsdata',
            name='current_silver_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='metalsdata',
            name='rates',
            field=models.JSONField(default=dict),
        ),
    ]
