# Generated by Django 5.0.6 on 2024-07-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_remove_gold_sell_price_remove_gold_sold_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='id',
        ),
        migrations.AddField(
            model_name='sale',
            name='sell_id',
            field=models.IntegerField(default=0, editable=False, primary_key=True, serialize=False),
        ),
    ]
