# Generated by Django 5.0.6 on 2024-07-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_remove_sale_id_sale_sell_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_sold',
            field=models.DateField(default=None),
        ),
    ]
