# Generated by Django 5.0.4 on 2024-04-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_gold_weight_per_unit_platinum_weight_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gold',
            name='weight_per_unit',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='platinum',
            name='weight_per_unit',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='silver',
            name='weight_per_unit',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
    ]
