# Generated by Django 5.0.4 on 2024-04-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_alter_gold_weight_per_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gold',
            name='weight_per_unit',
        ),
        migrations.RemoveField(
            model_name='platinum',
            name='weight_per_unit',
        ),
        migrations.RemoveField(
            model_name='silver',
            name='weight_per_unit',
        ),
    ]
