# Generated by Django 5.0.6 on 2024-07-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_sale_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_sold',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sell_id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
