# Generated by Django 5.0.4 on 2024-04-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_remove_gold_weight_per_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gold',
            name='item_type',
            field=models.CharField(choices=[('bar', 'Bar'), ('round', 'Round'), ('misc', 'Misc')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='platinum',
            name='item_type',
            field=models.CharField(choices=[('bar', 'Bar'), ('round', 'Round'), ('misc', 'Misc')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='silver',
            name='item_type',
            field=models.CharField(choices=[('bar', 'Bar'), ('round', 'Round'), ('misc', 'Misc')], default='', max_length=100),
        ),
    ]
