# Generated by Django 5.0.6 on 2024-07-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_alter_sale_date_sold_alter_sale_sell_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='spot_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='platinum',
            name='cost_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='platinum',
            name='total_cost_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
