# Generated by Django 5.0.4 on 2024-04-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_gold_item_type_platinum_item_type_silver_item_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gold',
            name='AGW',
        ),
        migrations.RemoveField(
            model_name='platinum',
            name='APtW',
        ),
        migrations.RemoveField(
            model_name='silver',
            name='ASW',
        ),
        migrations.AlterField(
            model_name='gold',
            name='purity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='gold',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='gold',
            name='weight_troy_oz',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='platinum',
            name='purity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='platinum',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='silver',
            name='purity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='silver',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
