# Generated by Django 5.0.6 on 2024-07-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_sale_spot_price_alter_platinum_cost_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
