# Generated by Django 5.0.6 on 2024-07-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_alter_sale_sell_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='profit',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='sale',
            name='spot_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
