# Generated by Django 5.0.6 on 2024-07-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_alter_sale_profit_alter_sale_spot_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
    ]
