# Generated by Django 5.0.6 on 2024-08-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_alter_sale_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gold',
            name='agw',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=30),
        ),
        migrations.AddField(
            model_name='gold',
            name='serial_number',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='platinum',
            name='apw',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=30),
        ),
        migrations.AddField(
            model_name='platinum',
            name='serial_number',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='silver',
            name='asw',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=30),
        ),
        migrations.AddField(
            model_name='silver',
            name='serial_number',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
