# Generated by Django 5.0.4 on 2024-05-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_alter_gold_id_alter_platinum_id_alter_silver_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gold',
            name='featured_image',
            field=models.ImageField(blank=True, default='images/gold_avatar.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='platinum',
            name='featured_image',
            field=models.ImageField(blank=True, default='images/platinum_avatar', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='silver',
            name='featured_image',
            field=models.ImageField(blank=True, default='images/silver_avatar.jpg', null=True, upload_to=''),
        ),
    ]
