# Generated by Django 5.0.6 on 2024-05-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0025_gold_item_about_platinum_item_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gold',
            name='item_about',
            field=models.TextField(blank=True, default='', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='platinum',
            name='item_about',
            field=models.TextField(blank=True, default='', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='silver',
            name='item_about',
            field=models.TextField(blank=True, default='', max_length=600, null=True),
        ),
    ]
