# Generated by Django 5.0.6 on 2024-05-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0027_gold_sold_to_platinum_sold_to_silver_sold_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gold',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='gold',
            name='sold_to',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='platinum',
            name='sold_to',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='silver',
            name='sold_to',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
