# Generated by Django 5.0.6 on 2024-05-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0028_alter_gold_sell_price_alter_gold_sold_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gold',
            name='weight_grams',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='platinum',
            name='weight_grams',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='silver',
            name='weight_grams',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
