# Generated by Django 5.0.6 on 2024-05-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0029_gold_weight_grams_platinum_weight_grams_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gold',
            name='item_year',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='platinum',
            name='item_year',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='silver',
            name='item_year',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
