# Generated by Django 5.0.6 on 2024-06-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0030_alter_gold_item_year_alter_platinum_item_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='silver',
            name='premium',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='silver',
            name='spot_at_purchase',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='silver',
            name='spot_at_sell',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True),
        ),
    ]
