# Generated by Django 5.0.6 on 2024-06-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0031_silver_premium_silver_spot_at_purchase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='silver',
            name='spot_at_sell',
        ),
        migrations.AddField(
            model_name='gold',
            name='premium',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='gold',
            name='spot_at_purchase',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='platinum',
            name='premium',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='platinum',
            name='spot_at_purchase',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True),
        ),
    ]
