# Generated by Django 5.0.6 on 2024-06-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0032_remove_silver_spot_at_sell_gold_premium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gold',
            name='cost_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='platinum',
            name='cost_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='silver',
            name='cost_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
    ]
