# Generated by Django 5.0.6 on 2024-06-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0033_gold_cost_per_unit_platinum_cost_per_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gold',
            name='initial_weight_unit',
            field=models.CharField(choices=[('GRAMS', 'Grams'), ('TROY_OUNCES', 'Troy Ounces')], default='TROY_OUNCES', max_length=50),
        ),
        migrations.AddField(
            model_name='platinum',
            name='initial_weight_unit',
            field=models.CharField(choices=[('GRAMS', 'Grams'), ('TROY_OUNCES', 'Troy Ounces')], default='TROY_OUNCES', max_length=50),
        ),
        migrations.AddField(
            model_name='silver',
            name='initial_weight_unit',
            field=models.CharField(choices=[('GRAMS', 'Grams'), ('TROY_OUNCES', 'Troy Ounces')], default='TROY_OUNCES', max_length=50),
        ),
    ]
