# Generated by Django 5.0.6 on 2024-06-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0034_gold_initial_weight_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gold',
            name='coa_present',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=100),
        ),
        migrations.AddField(
            model_name='platinum',
            name='coa_present',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=100),
        ),
        migrations.AddField(
            model_name='silver',
            name='coa_present',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='gold',
            name='weight_grams',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gold',
            name='weight_troy_oz',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='platinum',
            name='weight_grams',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='platinum',
            name='weight_troy_oz',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='silver',
            name='weight_grams',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='silver',
            name='weight_troy_oz',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
    ]
