# Generated by Django 5.0.6 on 2024-06-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0035_gold_coa_present_platinum_coa_present_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gold',
            name='item_type',
            field=models.CharField(choices=[('bar', 'Bar'), ('round', 'Round'), ('misc', 'Misc')], default='round', max_length=100),
        ),
        migrations.AlterField(
            model_name='platinum',
            name='item_type',
            field=models.CharField(choices=[('bar', 'Bar'), ('round', 'Round'), ('misc', 'Misc')], default='round', max_length=100),
        ),
        migrations.AlterField(
            model_name='silver',
            name='item_type',
            field=models.CharField(choices=[('bar', 'Bar'), ('round', 'Round'), ('misc', 'Misc')], default='round', max_length=100),
        ),
    ]
