# Generated by Django 5.0.6 on 2024-06-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0036_alter_gold_item_type_alter_platinum_item_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gold',
            name='date_sold',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platinum',
            name='date_sold',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='silver',
            name='date_sold',
            field=models.DateField(blank=True, null=True),
        ),
    ]
