# Generated by Django 5.0.6 on 2024-06-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0037_gold_date_sold_platinum_date_sold_silver_date_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='gold',
            name='weight_per_unit',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='platinum',
            name='weight_per_unit',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='silver',
            name='weight_per_unit',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gold',
            name='weight_grams',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='gold',
            name='weight_troy_oz',
            field=models.DecimalField(decimal_places=4, max_digits=30),
        ),
        migrations.AlterField(
            model_name='platinum',
            name='weight_grams',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='platinum',
            name='weight_troy_oz',
            field=models.DecimalField(decimal_places=4, max_digits=30),
        ),
        migrations.AlterField(
            model_name='silver',
            name='weight_grams',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='silver',
            name='weight_troy_oz',
            field=models.DecimalField(decimal_places=4, max_digits=30),
        ),
    ]
