# Generated by Django 5.0.6 on 2024-06-12 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0041_gold_sold_to_platinum_sold_to_silver_sold_to'),
    ]

    operations = [
    ]
