# Generated by Django 5.0.6 on 2024-06-12 11:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0042_auto_20240612_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_sold',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='object_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
